
service: apollo-gateway
frameworkVersion: '2'

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4002

provider:
  name: aws
  runtime: nodejs12.x

functions:
  graphql:
    handler: graphql.graphqlHandler
    events:
    - http:
        path: gateway
        method: post
        cors: true
    - http:
        path: gateway
        method: get
        cors: true